### ISSUE TITLE
交互逻辑建议

### ISSUE THREAD

**Issue by oqyj** [qiaoanqiao/codevar#1]
我有10个字段，每次都需要
1.激活输入框
2.输入xh
3.输入文字
4.选择复制后自动关闭
如此重复   每次都有多余的12步骤操作

建议不自动关闭或者像添加翻译插件一样的交互窗口

**Comment by qiaoanqiao** [comment]
很高兴你能提出建议，让插件能越来越好。

关于你的建议，为了下次更新少写点代码我有几点反驳😏

- 如果你在下次使用utools时是用来打开或使用其他功能，如果实现你的建议，体验会不好
- 如果下次你需要使用本插件别的功能，如果实现你的建议你需要进行更多操作
- 翻译插件是为了长篇输入，可能会断断续续的。而本插件应用场景一般不需要




当然这个功能我下次还是会更新，增加一个配置项。祝你用的开心，别忘了start。

**Comment by WintelZhao** [comment]
输入：xt、dt、xh、cl时，翻译的命名方式正常；
输入：小驼峰、大驼峰、下划线、常量时，只有翻译，而没有以对应的命名方式展现结果。

**Comment by qiaoanqiao** [comment]
> 输入：xt、dt、xh、cl时，翻译的命名方式正常；
> 输入：小驼峰、大驼峰、下划线、常量时，只有翻译，而没有以对应的命名方式展现结果。

**Comment by qiaoanqiao** [comment]
0.0.8版本修复咯

**Comment by WintelZhao** [comment]
0.0.8版发布了吗？uTools插件中自动更新？

**Comment by qiaoanqiao** [comment]
> 0.0.8版发布了吗？uTools插件中自动更新？

在审核, 很快就好了

**Comment by qiaoanqiao** [comment]
在审核, 很快就好了
