### ISSUE TITLE
记录一下翻译无响应的解决过程

### ISSUE THREAD

**Issue by itldg** [qiaoanqiao/codevar#11]
平日里一直正常使用,这几天突然没效果了

下载源码运行后发现是有道接口返回了500错误

出错请求

![3219435e9cd77c344692bc710916420](https://user-images.githubusercontent.com/13432299/178923230-79a7b237-9599-4d7d-bdcf-ca12d0837772.png)

正确请求

![138e0899308bc5afc866c6c098a84bb](https://user-images.githubusercontent.com/13432299/178923279-355237bf-e757-446b-afa7-f3a21d55aea1.png)

经过对比发现,出现异常的MAC电脑启用了IPV6

使用IPV6访问有道时才会返回500错误

临时解决方案,关闭IPV6的外网

![修改方法](https://user-images.githubusercontent.com/13432299/178923161-47b68d90-6cc0-4d55-8c7f-f86af98609fb.png)

恢复正常

**Comment by qiaoanqiao** [comment]
破案了哈哈哈, 谢谢谢谢

**Comment by strive1216** [comment]
直接改本地host不就行了，ipv6 是必不能关掉的😄

**Comment by itldg** [comment]
> 

自然也是可以的,关闭ipv6也是临时的方法,应该是有道单方面的问题,以前开着ipv6也是正常的
关闭ipv6操作简单一些
