### ISSUE TITLE
剔除结果中的特殊字符

### ISSUE THREAD

**Issue by itldg** [qiaoanqiao/codevar#13]
如`'`,`-`等

该情况不常见,列举几个偶然看到的异常结果

![image](https://user-images.githubusercontent.com/13432299/181410575-7869a9ab-b0fc-49c3-8e1d-ec3ec26dfaa0.png)

![image](https://user-images.githubusercontent.com/13432299/181410603-be093db8-f0cb-486e-a442-57f08b085ac0.png)

**Comment by itldg** [comment]
![image](https://user-images.githubusercontent.com/13432299/182273331-12c36338-838b-4a8b-b5f6-bd6a4155826b.png)

**Comment by qiaoanqiao** [comment]
已优化, 新版本见
