### ISSUE TITLE
一些小问题和改进建议汇总

### ISSUE THREAD

**Issue by itldg** [qiaoanqiao/codevar#16]
## 中文入口功能失效
<img width="187" alt="image" src="https://user-images.githubusercontent.com/13432299/182275735-3cf05450-7402-4ad4-af0f-493273cf0a73.png">
通过中文进入小驼峰,常量等,输入内容无反应

## [建议]统一显示
![image](https://user-images.githubusercontent.com/13432299/182275617-5d6f9f83-9567-414e-8cc1-94652309a5f8.png)
<img width="443" alt="image" src="https://user-images.githubusercontent.com/13432299/182275624-52f2b75f-f59f-4321-a536-99790f8656cf.png">
无论入口是哪一个,统一显示中文名

## 删除结果中出现的各种特殊符号
![image](https://user-images.githubusercontent.com/13432299/182275932-0d6d7e04-f037-44bb-a0bb-726db1ec1c1b.png)

## [建议]增加一个简单翻译,直接显示原始结果的翻译

**Comment by qiaoanqiao** [comment]
中文入口功能失效 ok
输入内容过长会导致接口异常 ok
统一显示 没法改
删除结果中出现的各种特殊符号 已优化
结果会有中文字符 已优化百度的, 微软的考虑有简体和繁体,暂不优化,使用自动模式
增加一个简单翻译,直接显示原始结果的翻译 后面考虑新增
