### ISSUE TITLE
在linux下自动复制到剪切板有问题

### ISSUE THREAD

**Issue by 0x7a7a** [qiaoanqiao/codevar#3]
无论是选中后按回车,还是用ALT+数字键选择,输出的内容都会是我最后一次手动复制的东西,并不是变量翻译后的结果  
版本是:0.1.2   
系统是:arch+i3wm  
提供点线索:其中一个翻译插件 在翻译结果中可以用ctrl+c复制,它这个复制是有效的

**Comment by qiaoanqiao** [comment]
你查看下触发键盘记录

**Comment by xujunhe** [comment]
我也是同样的问题

**Comment by qiaoanqiao** [comment]
需要提供详细信息

**Comment by pacmanzou** [comment]
我的是manjaro+i3wm
更新了现在这个utools v1.1.3最新版的
这个插件也不好使了 和上面出现的问题一样 
以前很正常
