### ISSUE TITLE
一点小建议~

### ISSUE THREAD

**Issue by qianzai** [qiaoanqiao/codevar#6]
这个小插件非常好用，但是每次都需要先输出 ，xh，xt，dt，等等这些感觉是不太好的，希望可以直接输入的变量时候，下面出现xh，xt等等规范的变量，这样可能会更好,类似idea的某个插件
![image](https://user-images.githubusercontent.com/46664739/100970707-6a3e2900-3570-11eb-91dc-0cfa68ac1d8b.png)

**Comment by qiaoanqiao** [comment]
两边各有特点吧. 暂时没有打算增加这个功能
