### ISSUE TITLE
每次复制完结果之后，都会自动关闭窗口（分离窗口也会关闭），导致多次使用很麻烦

### ISSUE THREAD

**Issue by wxbool** [qiaoanqiao/codevar#7]
![image](https://user-images.githubusercontent.com/29696787/114122421-cbad4480-9922-11eb-9dca-5069b043ec2c.png)

**Comment by qiaoanqiao** [comment]
选择合适的自动复制关闭是我开发时候的习惯, 设置模式暂时没打算编写.
