### ISSUE TITLE
选中变量后回车无法关闭页面并自动粘贴

### ISSUE THREAD

**Issue by xluos** [qiaoanqiao/codevar#9]
但是剪贴板里面已经有了 版本 0.1.8

**Comment by qiaoanqiao** [comment]
0.1.7版本已经更新, 需要你手动设置下才行了
1. 新增切换变量快速翻译命名插件是否自动关闭设置,默认自动关闭,打开需要查看关键词设置
2.新增切换变量快速翻译命名插件是否任意文本匹配插件可配合超级面板使用,默认关闭状态,打开需要查看关键词设置
